spring.application.name=ORDER-SERVICE
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.servlet.context-path=/

server.port=8078
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.instance-id=${spring.application.name}:${server.port}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/reactlibrarydatabase}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}


api.gateway.url=http://localhost:8090
cart.service.path =/api/cart
cart.service.url =http://CART-SERVICE/api/cart

user.service.path =/api/user/me
user.service.url =http://USER-SERVICE/api/user/me

book.service.path =/api/book
book.service.url =http://BOOK-SERVICE/api/book

payment.service.url = http://PAYMENT-SERVICE

# In order-service
internal.service.secret=${INTERNAL_SERVICE_SECRET}
gateway.communication.secret=${GATEWAY_COMMUNICATION_SECRET}

spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD:guest}

# Telemetry Configuration
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}
# ===== Distributed Tracing =====
management.tracing.sampling.probability=1.0
logging.pattern.correlation=[${spring.application.name:},%mdc{traceId:-},%mdc{spanId:-}]

# Pricing Configuration
pricing.tax.rate=0.18
pricing.shipping.rate=0.06

