spring.application.name=API-GATEWAY

server.port=8090
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.instance-id=${spring.application.name}:${server.port}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.cloud.discovery.enabled=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Swagger
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.enabled=true
springdoc.swagger-ui.urls[0].name=USER-SERVICE
springdoc.swagger-ui.urls[0].url=/USER-SERVICE/v3/api-docs
springdoc.swagger-ui.urls[1].name=BOOK-SERVICE
springdoc.swagger-ui.urls[1].url=/BOOK-SERVICE/v3/api-docs
springdoc.swagger-ui.urls[2].name=REVIEW-SERVICE
springdoc.swagger-ui.urls[2].url=/REVIEW-SERVICE/v3/api-docs
springdoc.swagger-ui.urls[3].name=CART-SERVICE
springdoc.swagger-ui.urls[3].url=/CART-SERVICE/v3/api-docs
springdoc.swagger-ui.urls[4].name=ORDER-SERVICE
springdoc.swagger-ui.urls[4].url=/ORDER-SERVICE/v3/api-docs
springdoc.swagger-ui.urls[5].name=PAYMENT-SERVICE
springdoc.swagger-ui.urls[5].url=/PAYMENT-SERVICE/v3/api-docs
springdoc.swagger-ui.urls[6].name=EMAIL-SERVICE
springdoc.swagger-ui.urls[6].url=/EMAIL-SERVICE/v3/api-docs

# Rate Limiter Thresholds
rate-limiter.login.capacity=5
rate-limiter.login.refill-tokens=5
rate-limiter.login.refill-duration-seconds=60

rate-limiter.auth.capacity=10
rate-limiter.auth.refill-tokens=10
rate-limiter.auth.refill-duration-seconds=60

rate-limiter.checkout.capacity=5
rate-limiter.checkout.refill-tokens=5
rate-limiter.checkout.refill-duration-seconds=60

rate-limiter.standard.capacity=100
rate-limiter.standard.refill-tokens=100
rate-limiter.standard.refill-duration-seconds=60

gateway.communication.secret=${GATEWAY_COMMUNICATION_SECRET}
internal.service.secret=${INTERNAL_SERVICE_SECRET}

# Telemetry Configuration
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}




# ===== Distributed Tracing =====
management.tracing.sampling.probability=1.0
logging.pattern.correlation=[${spring.application.name:},%mdc{traceId:-},%mdc{spanId:-}]
