spring.application.name=CART-SERVICE
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.servlet.context-path=/

server.port=8084
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.instance-id=${spring.application.name}:${server.port}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/reactlibrarydatabase}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

api.gateway.url=http://localhost:8090
book.service.bulk.path=/api/book/bulk
book.service.bulk.url=${api.gateway.url}${book.service.bulk.path}

logging.level.com.bookheaven=DEBUG

internal.service.secret=${INTERNAL_SERVICE_SECRET}
gateway.communication.secret=${GATEWAY_COMMUNICATION_SECRET}

# Telemetry Configuration
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=${spring.application.name}
# ===== Distributed Tracing =====
management.tracing.sampling.probability=1.0
logging.pattern.correlation=[${spring.application.name:},%mdc{traceId:-},%mdc{spanId:-}]
pricing.tax.rate=0.18
pricing.shipping.rate=0.06
