export const SERVICES = [
  {
    id: 'api-gateway',
    name: 'API Gateway',
    icon: '🌐',
    port: 8090,
    tech: 'Spring Cloud Gateway',
    color: '#818cf8',
    colorDim: 'rgba(129, 140, 248, 0.15)',
    description: 'Edge proxy — routes, rate-limits, and validates JWTs before forwarding to microservices.',
    tables: [],
    endpoints: [
      { method: 'ALL', path: '/api/user/**', desc: '→ USER-SERVICE', auth: 'Varies' },
      { method: 'ALL', path: '/api/book/**', desc: '→ BOOK-SERVICE', auth: 'Varies' },
      { method: 'ALL', path: '/api/cart/**, /api/coupons/**', desc: '→ CART-SERVICE', auth: 'JWT' },
      { method: 'ALL', path: '/api/order/**', desc: '→ ORDER-SERVICE', auth: 'JWT' },
      { method: 'ALL', path: '/api/payment/**', desc: '→ PAYMENT-SERVICE', auth: 'Varies' },
      { method: 'ALL', path: '/api/reviews/**', desc: '→ REVIEW-SERVICE', auth: 'Public' },
    ],
    entities: [],
    events: [],
    redisKeys: [],
    rateLimits: [
      { name: 'LOGIN', limit: '5 req/min', bucket: '5 tokens, refill 5 per 60s' },
      { name: 'AUTH', limit: '10 req/5min', bucket: '10 tokens, refill 10 per 300s' },
      { name: 'CHECKOUT', limit: '3 req/min', bucket: '3 tokens, refill 3 per 60s' },
      { name: 'GENERAL', limit: '30 req/min', bucket: '30 tokens, refill 30 per 60s' },
    ],
    details: 'The API Gateway is the single entry point for all client requests. It runs on Spring Cloud Gateway (reactive, Netty-based) and performs three key functions:\n\n1. **Routing** — Maps URL patterns to Eureka service names via `RouteLocator` configuration.\n2. **Rate Limiting** — Uses Bucket4j sliding window algorithm, keyed by IP address (from X-Forwarded-For header).\n3. **JWT Validation** — Extracts JWT from Authorization header or accessToken cookie, then injects X-User-Id, X-User-Email, and X-User-Role headers downstream.\n4. **Gateway Secret** — Injects X-Gateway-Secret header on all proxied requests to prove origin.\n\nCORS is configured to allow the React frontend at http://localhost:5173.',
  },
  {
    id: 'user-service',
    name: 'User Service',
    icon: '👤',
    port: 8081,
    tech: 'Spring Boot',
    color: '#34d399',
    colorDim: 'rgba(52, 211, 153, 0.15)',
    description: 'Handles authentication (JWT/OTP/OAuth2), user profiles, addresses, wishlist, and contact forms. Supports Google social login.',
    tables: ['users', 'user_roles', 'addresses', 'user_wishlist'],
    endpoints: [
      { method: 'POST', path: '/api/user/auth/sign-up', desc: 'Initiate signup (sends OTP)', auth: 'None' },
      { method: 'POST', path: '/api/user/auth/verify-otp', desc: 'Verify OTP + create user', auth: 'None' },
      { method: 'POST', path: '/api/user/login/login', desc: 'Authenticate user', auth: 'None' },
      { method: 'POST', path: '/api/user/auth/refresh', desc: 'Refresh access token', auth: 'Cookie' },
      { method: 'POST', path: '/api/user/auth/logout', desc: 'Invalidate session', auth: 'Cookie' },
      { method: 'POST', path: '/api/user/auth/forgot-password', desc: 'Send reset email', auth: 'None' },
      { method: 'POST', path: '/api/user/auth/reset-password', desc: 'Reset password via token', auth: 'None' },
      { method: 'GET', path: '/api/user/me', desc: 'Get current user profile', auth: 'JWT' },
      { method: 'GET', path: '/api/user/{id}', desc: 'Get user by UUID', auth: 'JWT' },
      { method: 'PUT', path: '/api/user/{id}', desc: 'Update user profile', auth: 'JWT' },
      { method: 'DELETE', path: '/api/user/{id}', desc: 'Delete user', auth: 'JWT' },
      { method: 'POST', path: '/api/user/me/change-password', desc: 'Change password', auth: 'JWT' },
      { method: 'POST', path: '/api/user/me/profile-picture', desc: 'Upload profile picture', auth: 'JWT' },
      { method: 'POST', path: '/api/user/address', desc: 'Add address', auth: 'JWT' },
      { method: 'PUT', path: '/api/user/address/{addressId}', desc: 'Update address', auth: 'JWT' },
      { method: 'DELETE', path: '/api/user/address/{addressId}', desc: 'Delete address', auth: 'JWT' },
      { method: 'POST', path: '/api/user/contact', desc: 'Submit contact form', auth: 'None' },
      { method: 'POST', path: '/api/user/wishlist/{bookId}', desc: 'Add to wishlist', auth: 'JWT' },
      { method: 'DELETE', path: '/api/user/wishlist/{bookId}', desc: 'Remove from wishlist', auth: 'JWT' },
      { method: 'GET', path: '/api/user/wishlist', desc: 'Get wishlist book IDs', auth: 'JWT' },
      { method: 'GET', path: '/api/user/wishlist/details', desc: 'Get wishlist with book details', auth: 'JWT' },
      { method: 'POST', path: '/api/user/auth/oauth2/callback', desc: 'OAuth2 social login (Google)', auth: 'None' },
    ],
    entities: [
      { name: 'User', fields: [
        { name: 'id', type: 'UUID', constraint: 'PK' },
        { name: 'username', type: 'VARCHAR(50)', constraint: '' },
        { name: 'email', type: 'VARCHAR(100)', constraint: 'UNIQUE' },
        { name: 'password', type: 'VARCHAR(255)', constraint: 'BCrypt' },
        { name: 'first_name', type: 'VARCHAR(50)', constraint: '' },
        { name: 'last_name', type: 'VARCHAR(50)', constraint: '' },
        { name: 'phone_number', type: 'VARCHAR(15)', constraint: '' },
        { name: 'roles', type: 'Set<Role>', constraint: 'USER|ADMIN|SELLER' },
        { name: 'auth_provider', type: 'ENUM', constraint: 'LOCAL|GOOGLE' },
        { name: 'provider_id', type: 'VARCHAR(255)', constraint: 'OAuth provider user ID' },
        { name: 'profile_picture', type: 'MEDIUMTEXT', constraint: 'Base64 / URL' },
        { name: 'razorpay_account_id', type: 'VARCHAR(100)', constraint: '' },
        { name: 'wishlist', type: 'Set<Long>', constraint: 'Book IDs' },
      ]},
      { name: 'Address', fields: [
        { name: 'id', type: 'BIGINT', constraint: 'PK' },
        { name: 'user_id', type: 'UUID', constraint: 'FK → users' },
        { name: 'street', type: 'VARCHAR(100)', constraint: '' },
        { name: 'city', type: 'VARCHAR(50)', constraint: '' },
        { name: 'state', type: 'VARCHAR(50)', constraint: '' },
        { name: 'zip_code', type: 'VARCHAR(10)', constraint: '' },
        { name: 'country', type: 'VARCHAR(50)', constraint: '' },
      ]},
    ],
    events: [
      { name: 'WelcomeEmailEvent', direction: 'produces', exchange: 'email.exchange', key: 'email.welcome' },
      { name: 'ContactEmailEvent', direction: 'produces', exchange: 'email.exchange', key: 'contact.key' },
    ],
    redisKeys: [
      { key: 'signup:{email}', ttl: '30 min', purpose: 'Temporary signup session data' },
      { key: 'otp:{email}', ttl: '5 min', purpose: 'BCrypt-hashed OTP' },
      { key: 'otp:cooldown:{email}', ttl: '1 min', purpose: 'OTP request cooldown' },
      { key: 'otp:count:{email}', ttl: '15 min', purpose: 'OTP rate limit counter (max 5)' },
      { key: 'refresh:{email}', ttl: '7 days', purpose: 'Active refresh token' },
      { key: 'password_reset:{token}', ttl: '30 min', purpose: 'Password reset token → email' },
      { key: 'email_token:{email}', ttl: '30 min', purpose: 'Reverse lookup: email → reset token' },
    ],
    details: 'The User Service is the central authentication and identity provider. It supports:\n\n• **OTP-based signup** — BCrypt-hashed OTPs stored in Redis with 5-minute TTL, 1-minute cooldown between sends, max 5 OTPs per 15 minutes.\n• **OAuth2 Social Login** — Google sign-in via Authorization Code Flow. Frontend redirects to Google → user grants consent → frontend receives auth code → backend exchanges code for access token → fetches profile → finds or creates user → issues JWT.\n• **Account Conflict Policy** — If OAuth email matches an existing account, login is rejected with a message directing the user to their original sign-in method (no auto-linking for security).\n• **JWT tokens** — Access token (1 day, in httpOnly cookie) + Refresh token (7 days, in cookie + Redis).\n• **Password reset** — UUID token stored in Redis (30 min), sent via Email Service.\n• **Profile management** — Profile pictures stored as base64 MEDIUMTEXT (max 2MB) or URL from Google profile.\n• **Wishlist** — Stored as Set<Long> of book IDs in an ElementCollection table.\n• **Contact form** — Published to RabbitMQ for async email delivery.\n• **Security** — JwtAuthFilter validates X-Service-Secret (internal) or X-Gateway-Secret (gateway) headers. Direct access returns 403. OAuth users are blocked from password login endpoint.',
  },
  {
    id: 'book-service',
    name: 'Book Service',
    icon: '📚',
    port: 8079,
    tech: 'Spring Boot',
    color: '#fbbf24',
    colorDim: 'rgba(251, 191, 36, 0.15)',
    description: 'Manages the book catalog, seller listings, search, stock inventory, and rating synchronization.',
    tables: ['books', 'seller_listings'],
    endpoints: [
      { method: 'GET', path: '/api/book', desc: 'Paginated book list', auth: 'None' },
      { method: 'GET', path: '/api/book/{bookId}', desc: 'Book detail + listings', auth: 'None' },
      { method: 'GET', path: '/api/book/search', desc: 'Search by title/author/isbn/category', auth: 'None' },
      { method: 'POST', path: '/api/book', desc: 'Add listing (auto-create book by ISBN)', auth: 'JWT' },
      { method: 'PUT', path: '/api/book/listing/{listingId}', desc: 'Update listing', auth: 'JWT' },
      { method: 'DELETE', path: '/api/book/listing/{listingId}', desc: 'Delete listing', auth: 'JWT' },
      { method: 'GET', path: '/api/book/seller', desc: 'Seller\'s own listings', auth: 'JWT' },
      { method: 'PUT', path: '/api/book/{bookId}', desc: 'Update book metadata (Admin)', auth: 'JWT' },
      { method: 'POST', path: '/api/book/bulk', desc: 'Bulk fetch by listing IDs', auth: 'Internal' },
      { method: 'PUT', path: '/api/book/reduce-stock', desc: 'Reduce stock on confirmation', auth: 'Internal' },
      { method: 'PUT', path: '/api/book/restore-stock', desc: 'Restore stock on cancellation', auth: 'Internal' },
      { method: 'POST', path: '/api/book/internal/bulk-books', desc: 'Bulk fetch by book IDs', auth: 'Internal' },
    ],
    entities: [
      { name: 'Book', fields: [
        { name: 'id', type: 'BIGINT', constraint: 'PK' },
        { name: 'title', type: 'VARCHAR', constraint: 'NOT NULL, indexed' },
        { name: 'author', type: 'VARCHAR', constraint: 'NOT NULL, indexed' },
        { name: 'description', type: 'VARCHAR(2000)', constraint: '' },
        { name: 'category', type: 'VARCHAR', constraint: 'NOT NULL, indexed' },
        { name: 'img', type: 'LONGTEXT', constraint: 'Base64 image' },
        { name: 'isbn', type: 'VARCHAR(20)', constraint: 'UNIQUE, indexed' },
        { name: 'average_rating', type: 'DOUBLE', constraint: 'Default 0.0' },
        { name: 'total_reviews', type: 'INT', constraint: 'Default 0' },
      ]},
      { name: 'SellerListing', fields: [
        { name: 'id', type: 'BIGINT', constraint: 'PK' },
        { name: 'book_id', type: 'BIGINT', constraint: 'FK → books, indexed' },
        { name: 'seller_id', type: 'UUID', constraint: 'indexed' },
        { name: 'seller_username', type: 'VARCHAR', constraint: '' },
        { name: 'seller_email', type: 'VARCHAR', constraint: '' },
        { name: 'price', type: 'DOUBLE', constraint: 'NOT NULL, > 0' },
        { name: 'currency', type: 'VARCHAR(3)', constraint: 'ISO code' },
        { name: 'copies', type: 'INT', constraint: 'Total inventory' },
        { name: 'copies_available', type: 'INT', constraint: 'Available stock' },
      ]},
    ],
    events: [
      { name: 'BookRatingUpdateEvent', direction: 'consumes', exchange: 'book.rating.update.exchange', key: 'book.rating.update.routing.key' },
    ],
    redisKeys: [
      { key: 'books:list:page:{n}:size:{s}', ttl: '10 min', purpose: 'Paginated book listings cache' },
      { key: 'books:detail:{bookId}', ttl: '10 min', purpose: 'Book detail with all listings' },
      { key: 'books:seller:{id}:page:*', ttl: '10 min', purpose: 'Seller\'s own listings cache' },
    ],
    details: 'The Book Service implements a marketplace catalog model:\n\n• **Canonical Book** — Identified by ISBN. Contains metadata shared across all sellers (title, author, category, image).\n• **Seller Listings** — Each seller lists a book at their own price with their own inventory. Unique constraint: (book_id, seller_id).\n• **Stock Management** — `reduce-stock` (on order confirmation) and `restore-stock` (on cancellation) are atomic, transactional operations.\n• **Rating Sync** — Event-driven eventual consistency via RabbitMQ (consumes BookRatingUpdateEvent).\n• **Cache Strategy** — Aggressive Redis caching with pattern-based invalidation on any mutation.\n\nThe listing add flow normalizes ISBNs (strips hyphens/spaces), auto-creates books if ISBN is new, and prevents duplicate listings per seller.',
  },
  {
    id: 'cart-service',
    name: 'Cart Service',
    icon: '🛒',
    port: 8084,
    tech: 'Spring Boot',
    color: '#22d3ee',
    colorDim: 'rgba(34, 211, 238, 0.15)',
    description: 'Manages shopping carts, cart items, and coupon system with seller-specific discount logic.',
    tables: ['carts', 'cart_items', 'coupons'],
    endpoints: [
      { method: 'GET', path: '/api/cart', desc: 'Get cart (auto-creates)', auth: 'JWT' },
      { method: 'POST', path: '/api/cart/item', desc: 'Add item (increments if exists)', auth: 'JWT' },
      { method: 'PUT', path: '/api/cart/items/{listingId}', desc: 'Update quantity (0 = remove)', auth: 'JWT' },
      { method: 'DELETE', path: '/api/cart/items/{listingId}', desc: 'Remove item', auth: 'JWT' },
      { method: 'DELETE', path: '/api/cart', desc: 'Clear entire cart', auth: 'JWT' },
      { method: 'DELETE', path: '/api/cart/internal/{userId}', desc: 'Clear cart (from Order Service)', auth: 'Internal' },
      { method: 'POST', path: '/api/cart/coupon/{code}', desc: 'Apply coupon', auth: 'JWT' },
      { method: 'DELETE', path: '/api/cart/coupon', desc: 'Remove coupon', auth: 'JWT' },
      { method: 'POST', path: '/api/coupons', desc: 'Create coupon (Seller/Admin)', auth: 'JWT' },
      { method: 'GET', path: '/api/coupons', desc: 'List coupons', auth: 'JWT' },
      { method: 'GET', path: '/api/coupons/{code}', desc: 'Get coupon by code', auth: 'JWT' },
      { method: 'PATCH', path: '/api/coupons/{id}/toggle', desc: 'Toggle active status', auth: 'JWT' },
      { method: 'POST', path: '/api/coupons/{code}/increment-usage', desc: 'Increment usage count', auth: 'Internal' },
    ],
    entities: [
      { name: 'Cart', fields: [
        { name: 'cart_id', type: 'UUID', constraint: 'PK' },
        { name: 'user_id', type: 'UUID', constraint: 'UNIQUE, indexed' },
        { name: 'applied_coupon_code', type: 'VARCHAR(50)', constraint: 'Nullable' },
      ]},
      { name: 'CartItem', fields: [
        { name: 'cart_item_id', type: 'UUID', constraint: 'PK' },
        { name: 'cart_id', type: 'UUID', constraint: 'FK → carts' },
        { name: 'listing_id', type: 'BIGINT', constraint: 'Seller listing ID' },
        { name: 'quantity', type: 'INT', constraint: 'NOT NULL' },
      ]},
      { name: 'Coupon', fields: [
        { name: 'id', type: 'UUID', constraint: 'PK' },
        { name: 'code', type: 'VARCHAR(50)', constraint: 'UNIQUE' },
        { name: 'seller_id', type: 'UUID', constraint: 'Nullable (global if null)' },
        { name: 'discount_type', type: 'ENUM', constraint: 'PERCENTAGE | FLAT' },
        { name: 'discount_value', type: 'DOUBLE', constraint: '' },
        { name: 'max_discount_amount', type: 'DOUBLE', constraint: 'Cap for %' },
        { name: 'min_order_amount', type: 'DOUBLE', constraint: '' },
        { name: 'is_active', type: 'BOOLEAN', constraint: 'DB flag' },
        { name: 'status', type: 'ENUM', constraint: 'Computed: ACTIVE|INACTIVE|EXPIRED' },
        { name: 'start_date / expiry_date', type: 'TIMESTAMP', constraint: '' },
        { name: 'usage_limit / usage_count', type: 'INT', constraint: '' },
      ]},
    ],
    events: [],
    redisKeys: [],
    details: 'The Cart Service maintains per-user shopping carts with:\n\n• **Auto-creation** — GET /api/cart creates a new cart if none exists for the user.\n• **Coupon System** — Supports PERCENTAGE and FLAT discount types, with seller-specific coupons (only apply to items from that seller).\n• **Dynamic Coupon Status** — The status (ACTIVE, INACTIVE, EXPIRED) is computed dynamically in real-time based on `is_active`, `expiry_date`, and `usage_limit`.\n• **Price Calculation** — Subtotal → Discount → TaxableAmount → Tax (18% GST) → Shipping (6%) → Total. Rounded to 2 decimal places.\n• **Passive Validation** — On every getCart, the applied coupon is re-validated. If it has expired or exceeded usage limits, it\'s automatically removed.\n• **Book Service dependency** — Calls /api/book/bulk to fetch live book data for cart response.',
  },
  {
    id: 'order-service',
    name: 'Order Service',
    icon: '📦',
    port: 8078,
    tech: 'Spring Boot',
    color: '#fb7185',
    colorDim: 'rgba(251, 113, 133, 0.15)',
    description: 'Orchestrates the entire order lifecycle — checkout, payment, stock, emails, and seller notifications.',
    tables: ['orders', 'order_items'],
    endpoints: [
      { method: 'POST', path: '/api/order/checkout', desc: 'Checkout (create order + initiate payment)', auth: 'JWT' },
      { method: 'GET', path: '/api/order/{orderId}', desc: 'Get order (ownership check)', auth: 'JWT' },
      { method: 'GET', path: '/api/order/my-orders', desc: 'Get user orders (paginated)', auth: 'JWT' },
      { method: 'DELETE', path: '/api/order/{orderId}/cancel', desc: 'Cancel order (restore stock + refund)', auth: 'JWT' },
      { method: 'GET', path: '/api/order/seller', desc: 'Seller\'s orders (filtered view)', auth: 'JWT' },
      { method: 'PUT', path: '/api/order/seller/{orderId}/status', desc: 'Update order status (Seller)', auth: 'JWT' },
      { method: 'GET', path: '/api/order/admin/all', desc: 'All orders (filterable)', auth: 'JWT' },
      { method: 'PUT', path: '/api/order/admin/{orderId}/status', desc: 'Force update status (Admin)', auth: 'JWT' },
      { method: 'PUT', path: '/api/order/{orderId}/confirm', desc: 'Confirm order (from Payment)', auth: 'Internal' },
      { method: 'PUT', path: '/api/order/{orderId}/fail', desc: 'Fail order (from Payment)', auth: 'Internal' },
    ],
    entities: [
      { name: 'Order', fields: [
        { name: 'id', type: 'UUID', constraint: 'PK' },
        { name: 'order_reference', type: 'VARCHAR(6)', constraint: 'UNIQUE, alphanumeric' },
        { name: 'user_id', type: 'UUID', constraint: 'indexed' },
        { name: 'username', type: 'VARCHAR(50)', constraint: '' },
        { name: 'email', type: 'VARCHAR(100)', constraint: '' },
        { name: 'shipping_address', type: 'Embedded', constraint: 'ShippingAddress' },
        { name: 'status', type: 'ENUM', constraint: 'PENDING|CONFIRMED|SHIPPED|DELIVERED|FAILED|CANCELLED|REFUNDED' },
        { name: 'subtotal', type: 'DOUBLE', constraint: '' },
        { name: 'discount_amount', type: 'DOUBLE', constraint: '' },
        { name: 'coupon_code', type: 'VARCHAR(50)', constraint: '' },
        { name: 'tax_amount', type: 'DOUBLE', constraint: '18% GST' },
        { name: 'shipping_amount', type: 'DOUBLE', constraint: '6%' },
        { name: 'total_amount', type: 'DOUBLE', constraint: '' },
        { name: 'currency', type: 'VARCHAR(10)', constraint: '' },
        { name: 'payment_id', type: 'VARCHAR(100)', constraint: 'Razorpay ID' },
        { name: 'payment_method', type: 'VARCHAR(50)', constraint: '' },
      ]},
      { name: 'OrderItem', fields: [
        { name: 'id', type: 'BIGINT', constraint: 'PK' },
        { name: 'order_id', type: 'UUID', constraint: 'FK → orders' },
        { name: 'listing_id', type: 'BIGINT', constraint: '' },
        { name: 'book_id', type: 'BIGINT', constraint: '' },
        { name: 'title', type: 'VARCHAR(200)', constraint: '' },
        { name: 'author', type: 'VARCHAR(100)', constraint: '' },
        { name: 'quantity', type: 'INT', constraint: '' },
        { name: 'price', type: 'DOUBLE', constraint: '' },
        { name: 'seller_id', type: 'UUID', constraint: '' },
        { name: 'seller_username', type: 'VARCHAR', constraint: '' },
        { name: 'seller_email', type: 'VARCHAR', constraint: '' },
      ]},
    ],
    events: [
      { name: 'OrderTimeoutEvent', direction: 'produces', exchange: 'order.timeout.exchange', key: 'order.timeout' },
      { name: 'OrderConfirmedEvent', direction: 'produces', exchange: 'email.exchange', key: 'email.order.confirmed' },
      { name: 'PaymentFailedEvent', direction: 'produces', exchange: 'email.exchange', key: 'email.payment.failed' },
      { name: 'SellerOrderEvent', direction: 'produces', exchange: 'email.exchange', key: 'email.seller.order' },
      { name: 'OrderShippedEvent', direction: 'produces', exchange: 'email.exchange', key: 'email.order.shipped' },
      { name: 'OrderDeliveredEvent', direction: 'produces', exchange: 'email.exchange', key: 'email.order.delivered' },
      { name: 'OrderLedgerEvent', direction: 'produces', exchange: 'ledger.exchange', key: 'ledger.order.confirmed' },
      { name: 'OrderTimeoutEvent', direction: 'consumes', exchange: 'order.timeout.exchange', key: 'order.timeout.processing' },
    ],
    redisKeys: [],
    details: 'The Order Service is the orchestrator of the entire purchase lifecycle:\n\n• **Checkout** — Fetches cart, validates stock, fetches user addresses, creates PENDING order, publishes timeout event (60s), initiates payment.\n• **Timeout** — Uses RabbitMQ DLX pattern: order.timeout.queue (60s TTL) → dead letter → order.timeout.processing.queue → consumer checks if still PENDING → marks FAILED.\n• **Confirmation** — On payment.captured webhook: reduce stock, clear cart, increment coupon usage, send buyer + seller emails, publish ledger event.\n• **Cancellation** — Restores stock, initiates Razorpay refund if already CONFIRMED (→ REFUNDED), otherwise → CANCELLED.\n• **Seller View** — Filters order items to show only the seller\'s items with recalculated totals.\n• **Order Reference** — 6-character alphanumeric code, generated with SecureRandom, uniqueness guaranteed via DB check.',
  },
  {
    id: 'payment-service',
    name: 'Payment Service',
    icon: '💳',
    port: 8076,
    tech: 'Spring Boot + Razorpay',
    color: '#a78bfa',
    colorDim: 'rgba(167, 139, 250, 0.15)',
    description: 'Integrates with Razorpay for payment processing, webhook handling, refunds, and seller settlement pipeline.',
    tables: ['payments', 'seller_ledger'],
    endpoints: [
      { method: 'GET', path: '/api/payment/config', desc: 'Get payment keys (Aliased by Gateway)', auth: 'Public' },
      { method: 'POST', path: '/api/payment/initiate', desc: 'Create Razorpay order', auth: 'Internal' },
      { method: 'POST', path: '/api/payment/webhook', desc: 'Razorpay webhook handler', auth: 'Signature' },
      { method: 'POST', path: '/api/payment/refund', desc: 'Initiate Razorpay refund', auth: 'Internal' },
      { method: 'GET', path: '/api/payment/{orderId}', desc: 'Get payment by order', auth: 'JWT' },
      { method: 'POST', path: '/api/payment/admin/trigger-settlement', desc: 'Manual settlement trigger', auth: 'Internal' },
    ],
    entities: [
      { name: 'Payment', fields: [
        { name: 'id', type: 'UUID', constraint: 'PK' },
        { name: 'order_id', type: 'UUID', constraint: 'indexed' },
        { name: 'user_id', type: 'UUID', constraint: 'indexed' },
        { name: 'amount', type: 'DOUBLE', constraint: '' },
        { name: 'currency', type: 'VARCHAR(10)', constraint: '' },
        { name: 'status', type: 'ENUM', constraint: 'PENDING|SUCCESS|FAILED|REFUNDED' },
        { name: 'gateway_order_id', type: 'VARCHAR(100)', constraint: 'Razorpay order_id' },
        { name: 'gateway_payment_id', type: 'VARCHAR(100)', constraint: 'Razorpay payment_id' },
        { name: 'payment_method', type: 'VARCHAR(50)', constraint: 'UPI|CARD|NETBANKING' },
        { name: 'failure_reason', type: 'VARCHAR(255)', constraint: '' },
        { name: 'refund_id', type: 'VARCHAR(100)', constraint: 'Razorpay refund_id' },
      ]},
      { name: 'SellerLedger', fields: [
        { name: 'id', type: 'BIGINT', constraint: 'PK' },
        { name: 'order_id', type: 'UUID', constraint: 'indexed' },
        { name: 'order_item_id', type: 'BIGINT', constraint: '' },
        { name: 'seller_id', type: 'UUID', constraint: 'indexed' },
        { name: 'gross_amount', type: 'DOUBLE', constraint: '' },
        { name: 'seller_discount', type: 'DOUBLE', constraint: 'Default 0.0' },
        { name: 'commission_rate', type: 'DOUBLE', constraint: '10%' },
        { name: 'commission_amount', type: 'DOUBLE', constraint: '' },
        { name: 'net_payout', type: 'DOUBLE', constraint: 'gross - commission - discount' },
        { name: 'settlement_status', type: 'ENUM', constraint: 'PENDING|PROCESSING|SETTLED|FAILED' },
        { name: 'settlement_id', type: 'UUID', constraint: 'Batch ID' },
        { name: 'gateway_transfer_id', type: 'VARCHAR(100)', constraint: 'Razorpay transfer_id' },
      ]},
    ],
    events: [
      { name: 'OrderLedgerEvent', direction: 'consumes', exchange: 'ledger.exchange', key: 'ledger.order.confirmed' },
      { name: 'SellerPayoutEvent', direction: 'produces', exchange: 'seller-payout-exchange', key: 'payout.routing.key' },
      { name: 'SellerPayoutEvent', direction: 'consumes', exchange: 'seller-payout-exchange', key: 'payout.routing.key' },
      { name: 'MissingRazorpayIdEvent', direction: 'produces', exchange: 'email.exchange', key: 'email.missing.razorpay' },
    ],
    redisKeys: [],
    details: 'The Payment Service handles all financial operations:\n\n• **Initiation** — Creates a Razorpay order (amount converted to paise), saves Payment entity with PENDING status.\n• **Webhook** — Listens for payment.captured and payment.failed events. Verifies HMAC-SHA256 signature. Has idempotency guard (skips if already SUCCESS).\n• **Refund** — Calls Razorpay refund API, updates status to REFUNDED.\n• **Seller Ledger** — LedgerQueueConsumer creates per-item ledger entries with 10% platform commission. Seller-specific coupon discounts are allocated to the matching seller.\n• **EOD Settlement** — Scheduled at 23:50 daily. Groups PENDING ledger entries by seller, sets status to PROCESSING, publishes SellerPayoutEvent.\n• **Settlement Retry** — Scheduled at 12:00 daily. Resets FAILED ledger entries back to PENDING for automatic retry.\n• **Payout Execution** — PayoutQueueConsumer calls Razorpay Transfers API to route funds to seller\'s linked account. If no razorpayAccountId, marks FAILED and sends email notification.',
  },
  {
    id: 'email-service',
    name: 'Email Service',
    icon: '📧',
    port: 8082,
    tech: 'Spring Boot + RabbitMQ',
    color: '#f472b6',
    colorDim: 'rgba(244, 114, 182, 0.15)',
    description: 'Async email delivery via RabbitMQ consumers, with idempotency tracking and retry/DLQ support.',
    tables: [],
    endpoints: [
      { method: 'POST', path: '/api/email/send-otp', desc: 'Send OTP email', auth: 'Internal' },
      { method: 'POST', path: '/api/email/send-password-reset', desc: 'Send password reset email', auth: 'Internal' },
    ],
    entities: [],
    events: [
      { name: 'OrderConfirmedEvent', direction: 'consumes', exchange: 'email.exchange', key: 'email.order.confirmed' },
      { name: 'PaymentFailedEvent', direction: 'consumes', exchange: 'email.exchange', key: 'email.payment.failed' },
      { name: 'WelcomeEmailEvent', direction: 'consumes', exchange: 'email.exchange', key: 'email.welcome' },
      { name: 'SellerOrderEvent', direction: 'consumes', exchange: 'email.exchange', key: 'email.seller.order' },
      { name: 'OrderShippedEvent', direction: 'consumes', exchange: 'email.exchange', key: 'email.order.shipped' },
      { name: 'OrderDeliveredEvent', direction: 'consumes', exchange: 'email.exchange', key: 'email.order.delivered' },
      { name: 'ContactEmailEvent', direction: 'consumes', exchange: 'email.exchange', key: 'contact.key' },
      { name: 'MissingRazorpayIdEvent', direction: 'consumes', exchange: 'email.exchange', key: 'email.missing.razorpay' },
    ],
    redisKeys: [
      { key: 'processed:{messageId}', ttl: 'Permanent', purpose: 'Idempotency tracker for email deduplication' },
    ],
    details: 'The Email Service operates in two modes:\n\n1. **Synchronous REST API** — For OTP and password reset emails, called by User Service with X-Service-Secret header.\n2. **Async RabbitMQ Consumer** — For all transactional emails: order confirmation, payment failure, welcome, seller notifications, shipping updates, delivery confirmations, contact forms, and missing Razorpay ID alerts.\n\n**True Strategy Pattern** — Uses an O(1) Map-based registry dynamically populated at startup to resolve the correct EmailHandler without complex switch statements.\n\n**Idempotency** — Each message has a deterministic messageId. The ProcessedMessageTracker checks Redis before processing; if already processed, the message is skipped.\n\n**Retry** — 3 attempts with exponential backoff (1s → 2s → 4s). On final failure, message routes to Dead Letter Queue (email.dlq).\n\n**Templates** — HTML email templates use mustache-style placeholders ({{USERNAME}}, {{ORDER_ID}}, etc.).\n\n**Contact Form** — Supports base64 screenshot attachments, sent to configured admin email with reply-to set to the user\'s email.',
  },
  {
    id: 'search-service',
    name: 'Search Service',
    icon: '🔎',
    port: 8088,
    tech: 'Spring Boot + Elasticsearch',
    color: '#0ea5e9',
    colorDim: 'rgba(14, 165, 233, 0.15)',
    description: 'Provides lightning-fast full-text search capabilities over the book catalog using Elasticsearch.',
    tables: ['book_index (Elasticsearch)'],
    endpoints: [
      { method: 'GET', path: '/api/search', desc: 'Full-text search books', auth: 'None' },
    ],
    entities: [
      { name: 'BookDocument', fields: [
        { name: 'id', type: 'String', constraint: 'PK' },
        { name: 'title', type: 'String', constraint: 'Indexed' },
        { name: 'author', type: 'String', constraint: 'Indexed' },
        { name: 'category', type: 'String', constraint: 'Indexed' },
        { name: 'isbn', type: 'String', constraint: 'Indexed' },
      ]},
    ],
    events: [
      { name: 'BookEvent', direction: 'consumes', exchange: 'book.event.exchange', key: 'book.updated | book.created | book.deleted' },
    ],
    redisKeys: [],
    details: 'The Search Service offloads heavy text searching from the MySQL database by utilizing Elasticsearch.\n\n• **Sync** — It consumes BookEvents (Create/Update/Delete) from RabbitMQ to keep its Elasticsearch index in sync with the Book Service catalog.\n• **Fuzzy Search** — Implements fuzziness to handle typos in user searches.',
  },
  {
    id: 'review-service',
    name: 'Review Service',
    icon: '⭐',
    port: 8083,
    tech: 'Spring Boot',
    color: '#fb923c',
    colorDim: 'rgba(251, 146, 60, 0.15)',
    description: 'Book reviews with ratings, photo uploads, upvote system, and automatic rating sync to Book Service.',
    tables: ['reviews', 'review_photos', 'review_upvotes'],
    endpoints: [
      { method: 'GET', path: '/api/reviews/{bookId}', desc: 'Get reviews for book (paginated)', auth: 'None' },
      { method: 'POST', path: '/api/reviews', desc: 'Add review (with photos)', auth: 'JWT' },
      { method: 'PUT', path: '/api/reviews/{reviewId}', desc: 'Update own review', auth: 'JWT' },
      { method: 'DELETE', path: '/api/reviews/{reviewId}', desc: 'Delete own review', auth: 'JWT' },
      { method: 'POST', path: '/api/reviews/{reviewId}/upvote', desc: 'Toggle upvote', auth: 'JWT' },
    ],
    entities: [
      { name: 'Review', fields: [
        { name: 'id', type: 'BIGINT', constraint: 'PK' },
        { name: 'user_id', type: 'UUID', constraint: 'indexed' },
        { name: 'username', type: 'VARCHAR(100)', constraint: '' },
        { name: 'book_id', type: 'BIGINT', constraint: 'indexed' },
        { name: 'rating', type: 'DOUBLE', constraint: '1-5, validated' },
        { name: 'review_description', type: 'VARCHAR(5000)', constraint: '' },
        { name: 'photos', type: 'List<MEDIUMTEXT>', constraint: 'ElementCollection' },
        { name: 'upvotedUserIds', type: 'Set<UUID>', constraint: 'ElementCollection, UNIQUE per user' },
      ]},
    ],
    events: [
      { name: 'BookRatingUpdateEvent', direction: 'produces', exchange: 'book.rating.update.exchange', key: 'book.rating.update.routing.key' },
    ],
    redisKeys: [],
    details: 'The Review Service provides book reviews with:\n\n• **One review per user per book** — Enforced by unique constraint on (user_id, book_id).\n• **Rating sync** — After every add/update/delete, publishes a BookRatingUpdateEvent to RabbitMQ to securely update average_rating and total_reviews on the Book Service.\n• **Photo support** — Photos stored as base64 MEDIUMTEXT in review_photos ElementCollection table.\n• **Upvote system** — Toggle-based (add/remove). Stored in review_upvotes table with unique constraint per (review_id, user_id).\n• **Authorization** — Only the review author can update or delete their review.',
  },
  {
    id: 'eureka-server',
    name: 'Eureka Server',
    icon: '🔍',
    port: 8761,
    tech: 'Spring Cloud Netflix',
    color: '#64748b',
    colorDim: 'rgba(100, 116, 139, 0.15)',
    description: 'Service discovery and registration server. All microservices register here for load-balanced communication.',
    tables: [],
    endpoints: [],
    entities: [],
    events: [],
    redisKeys: [],
    details: 'Netflix Eureka Server running on port 8761.\n\n• Does NOT register itself (register-with-eureka=false, fetch-registry=false).\n• All services register with: eureka.client.service-url.defaultZone=http://localhost:8761/eureka\n• Instance IDs follow pattern: ${spring.application.name}:${server.port}\n• Enables client-side load balancing via @LoadBalanced RestTemplate beans in each service.',
  },
];

export const EVENTS = [
  { name: 'WelcomeEmailEvent', producer: 'User Service', consumer: 'Email Service', exchange: 'email.exchange', key: 'email.welcome', queue: 'email.order.welcome.queue' },
  { name: 'ContactEmailEvent', producer: 'User Service', consumer: 'Email Service', exchange: 'email.exchange', key: 'contact.key', queue: 'email.contact.queue' },
  { name: 'OrderTimeoutEvent', producer: 'Order Service', consumer: 'Order Service', exchange: 'order.timeout.exchange', key: 'order.timeout', queue: 'order.timeout.queue (60s TTL → DLX → processing)' },
  { name: 'OrderConfirmedEvent', producer: 'Order Service', consumer: 'Email Service', exchange: 'email.exchange', key: 'email.order.confirmed', queue: 'email.order.confirmed.queue' },
  { name: 'PaymentFailedEvent', producer: 'Order Service', consumer: 'Email Service', exchange: 'email.exchange', key: 'email.payment.failed', queue: 'email.payment.failed.queue' },
  { name: 'SellerOrderEvent', producer: 'Order Service', consumer: 'Email Service', exchange: 'email.exchange', key: 'email.seller.order', queue: 'email.seller.order.queue' },
  { name: 'OrderShippedEvent', producer: 'Order Service', consumer: 'Email Service', exchange: 'email.exchange', key: 'email.order.shipped', queue: 'email.order.shipped.queue' },
  { name: 'OrderDeliveredEvent', producer: 'Order Service', consumer: 'Email Service', exchange: 'email.exchange', key: 'email.order.delivered', queue: 'email.order.delivered.queue' },
  { name: 'OrderLedgerEvent', producer: 'Order Service', consumer: 'Payment Service', exchange: 'ledger.exchange', key: 'ledger.order.confirmed', queue: 'seller-ledger-queue' },
  { name: 'SellerPayoutEvent', producer: 'Payment Service', consumer: 'Payment Service', exchange: 'seller-payout-exchange', key: 'payout.routing.key', queue: 'seller-payout-queue' },
  { name: 'MissingRazorpayIdEvent', producer: 'Payment Service', consumer: 'Email Service', exchange: 'email.exchange', key: 'email.missing.razorpay', queue: 'email.missing.razorpay.queue' },
  { name: 'BookRatingUpdateEvent', producer: 'Review Service', consumer: 'Book Service', exchange: 'book.rating.update.exchange', key: 'book.rating.update.routing.key', queue: 'book.rating.update.queue' },
  { name: 'BookEvent', producer: 'Book Service', consumer: 'Search Service', exchange: 'book.event.exchange', key: 'book.*', queue: 'book.search.queue' },
];

export const EXCHANGES = [
  { name: 'email.exchange', type: 'Topic', declaredBy: 'Email Service', queues: 8, purpose: 'All email routing' },
  { name: 'email.dlx', type: 'Direct', declaredBy: 'Email Service', queues: 1, purpose: 'Dead letter for failed emails' },
  { name: 'order.timeout.exchange', type: 'Topic', declaredBy: 'Order Service', queues: 2, purpose: 'Order payment timeout (DLX pattern)' },
  { name: 'ledger.exchange', type: 'Topic', declaredBy: 'Order Service', queues: 1, purpose: 'Seller ledger entries' },
  { name: 'seller-payout-exchange', type: 'Topic', declaredBy: 'Payment Service', queues: 1, purpose: 'Seller payout execution' },
  { name: 'book.rating.update.exchange', type: 'Direct', declaredBy: 'Review Service', queues: 1, purpose: 'Eventual consistency for book ratings' },
  { name: 'book.event.exchange', type: 'Topic', declaredBy: 'Book Service', queues: 1, purpose: 'Syncing catalog updates to Search Service' },
];

export const DESIGN_DECISIONS = [
  {
    service: 'Resilience & Fault Tolerance',
    decisions: [
      {
        question: "Why do we use Resilience4j Circuit Breakers for internal microservice calls?",
        answer: "To prevent cascading failures. If a downstream service (like <code>book-service</code>) goes offline, we don't want the calling service (like <code>cart-service</code> or <code>user-service</code>) to exhaust its thread pool waiting for a timeout or to throw unhandled 500 Internal Server Errors. The Circuit Breaker detects the failure threshold, 'trips', and immediately returns a clean fallback response (like a 503 Service Unavailable) to the frontend, protecting the system from overload."
      }
    ]
  },
  {
    service: 'Global & Security',
    decisions: [
      {
        question: "Why store the refresh token in Redis when JWTs are inherently stateless?",
        answer: "<strong>1. Revocation & Logout:</strong> If a refresh token is purely stateless and not tracked in a database, a user cannot truly 'log out.' Even if the browser cookie is deleted, a stolen token remains mathematically valid until it expires (e.g., 7 days). By storing the token in Redis, we can instantly invalidate it upon logout by deleting the Redis key.<br/><br/><strong>2. Session Hijacking Prevention:</strong> If an account is compromised, the user can choose to log out of all devices. Storing tokens in Redis allows the backend to easily wipe all active sessions for that user.<br/><br/><strong>3. Single Active Session:</strong> We use a Redis key structured as <code>refresh:&lt;email&gt;</code>. This enforces a 'Single Active Session' rule per email. If a user logs into a new device, the old refresh token is automatically overwritten in Redis, immediately logging them out of the old device."
      }
    ]
  },
  {
    service: 'User Service',
    decisions: [
      {
        question: "Why do we throw an error when a user signs in with Google, but their email already exists under a Local password account?",
        answer: "For security against Account Takeover. If we automatically linked the new Google login to the existing local account, an attacker who manages to create a Google account with the victim's email could bypass the password and gain full access to their BookHeaven profile. We explicitly block auto-linking and force them to log in via their original method."
      },
      {
        question: "Why do we Bcrypt-hash the OTPs before storing them in Redis?",
        answer: "Even though Redis is an internal cache, storing raw OTPs leaves the system vulnerable to insider threats or if the cache is ever dumped/compromised. By hashing the OTP before saving, the backend can safely verify the user's input without ever storing the plaintext code anywhere."
      },
      {
        question: "Why are OTP emails sent synchronously via REST, but Welcome/Contact emails are sent asynchronously via RabbitMQ?",
        answer: "OTPs are time-critical and block the immediate user login/signup flow, so the backend needs immediate confirmation of success/failure before telling the frontend to render the 'Enter OTP' screen. Welcome and Contact emails are background tasks; publishing them to RabbitMQ offloads the work and ensures the HTTP request returns instantly for a snappy UI."
      },
      {
        question: "Why is the User's Wishlist stored as a simple `Set<Long>` instead of a `@ManyToMany` relationship with a `Book` entity?",
        answer: "Microservice decoupling. The `user-service` should not maintain or duplicate the schema of the `book-service`. Storing just the `bookId` keeps the User database lightweight. When full book details are needed, `user-service` makes a bulk internal API call to fetch the live titles, prices, and images."
      },
      {
        question: "How does the User Service prevent unauthorized direct access if it runs on an exposed port?",
        answer: "The `JwtAuthFilter` checks for an `X-Gateway-Secret` (or `X-Service-Secret`) header injected by the API Gateway. The Gateway actively strips this header from external incoming requests and injects its own secure token internally. This ensures all traffic is forced through the Gateway's JWT validation layer and rate limiters."
      },
      {
        question: "Why add the wishlist to user-service instead of book-service, despite book-service being the one who handles book related stuff?",
        answer: "Although the Wishlist holds book IDs, the Wishlist itself is fundamentally a <strong>User Profile Attribute</strong>, not a catalog attribute. It represents a specific user's personal intent to purchase, much like a Shopping Cart.<br/><br/>If we stored the Wishlist in the `book-service`, that service would be forced to maintain a mapping of `userId` to `bookId`, which creates a tight coupling between the global book catalog and individual user identities.<br/><br/>By keeping the Wishlist in `user-service`, we maintain clean domain boundaries (Domain-Driven Design):<br/>• <strong>`user-service`</strong> owns 'who the user is and what they want'.<br/>• <strong>`book-service`</strong> owns 'what the books are'.<br/><br/>When the frontend needs to display the wishlist, `user-service` simply makes a bulk API call to `book-service` saying 'Give me the live details (titles, prices) for these 5 book IDs'. This keeps the databases completely decoupled."
      }
    ]
  },
  {
    service: 'Cart Service',
    decisions: [
      {
        question: "Why is there a separate `/api/cart/internal/{userId}` endpoint for clearing the cart instead of reusing the standard `/api/cart` endpoint?",
        answer: "The standard `/api/cart` endpoint extracts the `userId` from the incoming user's JWT token via the `Authentication` object. When the `order-service` attempts to clear the cart in the background after a successful payment, it doesn't have the user's JWT token—it uses an internal system token (`X-Service-Secret`). This caused the cart service to mistakenly attempt to clear the cart of a dummy 'System User'. The new internal endpoint allows `order-service` to explicitly specify the target `userId` in the URL path, bypassing the need for a user session token."
      }
    ]
  },
  {
    service: 'API Gateway',
    decisions: [
      {
        question: "Why is there an alias route `/api/config/checkout-keys` that points to `/api/payment/config`?",
        answer: "<strong>Adblockers!</strong> Many browser extensions (like uBlock Origin) aggressively block any network requests containing the word 'payment' or 'checkout' in certain path configurations. Our initial payment configuration endpoint (`/api/payment/config`) was being blocked on the frontend, breaking the checkout flow initialization. We configured a rewrite rule (`RewritePath=/api/config/checkout-keys/(?<segment>.*), /api/payment/$\\{segment}`) in the API Gateway to alias this to a safe-sounding path, ensuring reliable delivery regardless of browser extensions."
      }
    ]
  }
];
